version: "3.9"
services:
  grafana:
    image: grafana/grafana-oss
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource,marcusolsson-json-datasource
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  api:
    build: .
    ports:
      - 443:443
    volumes:
      - type: bind
        source: /root/db
        target: /root/db
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: /etc/ssl
        target: /etc/ssl



volumes:
  grafana_data:
    driver: local
